spring:
  config:
    activate:
      on-profile: server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(Hjw62kH9gONiTofwncLNBhoFcbsruk/vA0gLeLrEzIWshO0UepsInOwoRpclfIkLssKxvmGeO2gyyD/e/dHWyTDeqzVTxHZWszilMI5A0hkHxB/JJnprO4IvPAxIDPVPnn+wKB11hWib7DiwM5jxfHe+S9bTCk37Rn+xwDTTHL9YGgdxePdAFg==)
    username: ENC(yZJyWJKk2dEesymwREbn09M870O68mcP)
    password: ENC(svktEs0sRn7RTAaJ27B+6NQlMpG2oj5D)

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(m7MAk7Q/on58EdQOScdUWdMQHFZygJqe8Gu9AuUwHQsQn6HEPqwQcCkUJ2Gcft1zdNXAPeuzdoLHArjgEmxFtJiaFJLvdIpK7vTTcWyB1y3YqAwmEOjq6w==)
            client-secret: ENC(GjfkXPimdb4OQSXpumaUpd/nAapzTOButylcEFMTHZomrnnZdOy1QgOVdpoRBHLW)
            redirect-uri: https://cryptoptima.io/login/oauth2/code/google
            scope:
              - email
              - profile

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    key: {$key}
    property:
      prefix: ENC(
      suffix: )

jwt:
  key: ENC(q1WQtVFbAcxGIK0iKkOSnewowB8QWTKB/4+BHJduEuohwosoASHd1LWHss4WUywH98YoWwIkWgg=)
  accessTokenExpirationMinutes: 1
  refreshTokenExpirationMinutes: 2
