spring:
  config:
    activate:
      on-profile: server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(1jjseMd2BTxKQczEFR24CRjjKXoinElsFet5bjE7brFehXJRuXK0g7/gPNqGVMyjywZC41D2Du9nbPzTdRUbKC/L0s1EXc1nrvolnDSyIHI=)
    username: ENC(jQGXW82rCvB/bHond/3xkw==)
    password: ENC(iQ6hG+xiEn89rSOPMxK3og==)

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(m7MAk7Q/on58EdQOScdUWdMQHFZygJqe8Gu9AuUwHQsQn6HEPqwQcCkUJ2Gcft1zdNXAPeuzdoLHArjgEmxFtJiaFJLvdIpK7vTTcWyB1y3YqAwmEOjq6w==)
            client-secret: ENC(GjfkXPimdb4OQSXpumaUpd/nAapzTOButylcEFMTHZomrnnZdOy1QgOVdpoRBHLW)
            scope:
              - email
              - profile

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    key: {$key}
    property:
      prefix: ENC(
      suffix: )

jwt:
  key: ENC(q1WQtVFbAcxGIK0iKkOSnewowB8QWTKB/4+BHJduEuohwosoASHd1LWHss4WUywH98YoWwIkWgg=)
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 120