spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cryptoptima?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(m7MAk7Q/on58EdQOScdUWdMQHFZygJqe8Gu9AuUwHQsQn6HEPqwQcCkUJ2Gcft1zdNXAPeuzdoLHArjgEmxFtJiaFJLvdIpK7vTTcWyB1y3YqAwmEOjq6w==)
            client-secret: ENC(GjfkXPimdb4OQSXpumaUpd/nAapzTOButylcEFMTHZomrnnZdOy1QgOVdpoRBHLW)
            scope:
              - email
              - profile

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    key: {$key}
    property:
      prefix: ENC(
      suffix: )

jwt:
  key: ENC(q1WQtVFbAcxGIK0iKkOSnewowB8QWTKB/4+BHJduEuohwosoASHd1LWHss4WUywH98YoWwIkWgg=)
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 120